/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digitaluniversity.ui.faculty;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Business;
import model.UserAccount;

/**
 * @author rg
 * @author priyankavadivel
 * @author vedanarayananshrirangesh
 */
public class FacultyWorkAreaPanel extends javax.swing.JPanel {

    /**
     * @return parent panel for navigation
     */
    private JPanel getRoot() {
        return (JPanel) this.getClientProperty("root");
    }

    /**
     * @return current Business instance
     */
    private Business getBusiness() {
        return (Business) this.getClientProperty("business");
    }

    /**
     * @return current logged-in UserAccount
     */
    private UserAccount getAccount() {
        return (UserAccount) this.getClientProperty("account");
    }

    /**
     * Creates new form facultyWorkAreaPanel
     */
    public FacultyWorkAreaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudGrades = new javax.swing.JButton();
        btnManageCourses = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPerfReports = new javax.swing.JButton();
        btnTuitionInsights = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnStudGrades.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnStudGrades.setText("Student Grades");
        btnStudGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudGradesActionPerformed(evt);
            }
        });

        btnManageCourses.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnManageCourses.setText("Manage Courses");
        btnManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCoursesActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 204, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPerfReports.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnPerfReports.setText("Performance Reports");
        btnPerfReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfReportsActionPerformed(evt);
            }
        });

        btnTuitionInsights.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnTuitionInsights.setText("Tuition Insights");
        btnTuitionInsights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionInsightsActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnManageCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnStudGrades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPerfReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTuitionInsights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnLogout)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTuitionInsights, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfReports, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCoursesActionPerformed
        CourseMgmtPanel p = new CourseMgmtPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("courseMgmt", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "courseMgmt");
    }//GEN-LAST:event_btnManageCoursesActionPerformed

    private void btnStudGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudGradesActionPerformed
        StudentMgmtPanel smp = new StudentMgmtPanel();
        smp.putClientProperty("business", getBusiness());
        smp.putClientProperty("root", getRoot());
        smp.putClientProperty("account", getAccount());
        getRoot().add("studentMgmt", smp);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "studentMgmt");

    }//GEN-LAST:event_btnStudGradesActionPerformed

    private void btnPerfReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfReportsActionPerformed
        PerfReportingPanel p = new PerfReportingPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("performanceReports", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "performanceReports");
    }//GEN-LAST:event_btnPerfReportsActionPerformed

    private void btnTuitionInsightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionInsightsActionPerformed
        TuitionEnrollmentPanel p = new TuitionEnrollmentPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("tuitionInsights", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "tuitionInsights");
    }//GEN-LAST:event_btnTuitionInsightsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        ProfMgmtPanel p = new ProfMgmtPanel(); // optional future panel
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("facultyProfile", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "facultyProfile");
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        ((CardLayout) getRoot().getLayout()).previous(getRoot());
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCourses;
    private javax.swing.JButton btnPerfReports;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnStudGrades;
    private javax.swing.JButton btnTuitionInsights;
    // End of variables declaration//GEN-END:variables
}
