/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitaluniversity.ui;

import digitaluniversity.ui.common.LoginPanel;
import java.awt.CardLayout;
import model.Business;
import model.ConfigureTheBusiness;

/**
 * Main application frame that serves as the entry point for Digital University.
 * Initializes the business configuration and displays the login panel first.
 *
 * @author rg
 */
public class MainJFrame extends javax.swing.JFrame {

    private Business business;

    /**
     * Creates new MainJFrame and initializes components.
     * Sets up CardLayout navigation and loads the LoginPanel.
     */
    public MainJFrame() {
        initComponents();

         this.setLocationRelativeTo(null); // center window on screen
        this.business = ConfigureTheBusiness.init(); // initialize system data

        // Set layout and prepare login panel
        workAreaPanel.setLayout(new CardLayout());
        LoginPanel login = new LoginPanel();
        login.putClientProperty("business", business);
        login.putClientProperty("root", workAreaPanel);
        workAreaPanel.add("login", login);

        // Show login panel by default
        ((CardLayout) workAreaPanel.getLayout()).show(workAreaPanel, "login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workAreaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workAreaPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(workAreaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
