/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digitaluniversity.ui.admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Business;

/**
 *
 * @author priyankavadivel
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    public AdminWorkAreaPanel() {
        initComponents();
    }
    // Get the main container panel (root) that uses CardLayout
    private JPanel getRoot() {
        return (JPanel) this.getClientProperty("root");
    }
    // Get the Business object which holds system-wide data
    private Business getBusiness() {
        return (Business) this.getClientProperty("business");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageAccounts = new javax.swing.JButton();
        btnManagePeople = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnManageAccounts.setText("Manage User Accounts");
        btnManageAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccountsActionPerformed(evt);
            }
        });

        btnManagePeople.setText("Manage Students / Faculty");
        btnManagePeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePeopleActionPerformed(evt);
            }
        });

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnAnalytics.setText("Analytics Dashboard");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManagePeople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageAccounts)
                    .addComponent(btnManagePeople))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile)
                    .addComponent(btnAnalytics))
                .addGap(109, 109, 109)
                .addComponent(btnLogout)
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
     * Opens the Manage User Accounts Panel
     */
    private void btnManageAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccountsActionPerformed
        ManageUserAccountsPanel p = new ManageUserAccountsPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.refreshTable();
        getRoot().add("manageUserAccounts", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "manageUserAccounts");
    }//GEN-LAST:event_btnManageAccountsActionPerformed
/**
     * Opens the Admin Profile Panel
     */
    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        AdminProfilePanel p = new AdminProfilePanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", this.getClientProperty("account"));
        getRoot().add("adminProfile", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "adminProfile");
    }//GEN-LAST:event_btnProfileActionPerformed
/**
     * Opens the Manage People (Students and Faculty) Panel
     */
    private void btnManagePeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePeopleActionPerformed
        ManagePeopleRecordsPanel p = new ManagePeopleRecordsPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.refreshPeopleTables();
        getRoot().add("managePeople", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "managePeople");
    }//GEN-LAST:event_btnManagePeopleActionPerformed
/**
     * Opens the University Analytics Dashboard
     */
    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        UniversityAnalyticsPanel p = new UniversityAnalyticsPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.generateAction();
        getRoot().add("analytics", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "analytics");
    }//GEN-LAST:event_btnAnalyticsActionPerformed
/**
     * Logs out the user and returns to the login screen
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "login");
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAccounts;
    private javax.swing.JButton btnManagePeople;
    private javax.swing.JButton btnProfile;
    // End of variables declaration//GEN-END:variables
}
