/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digitaluniversity.ui.admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Business;

/**
 *
 * @author priyankavadivel
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    public AdminWorkAreaPanel() {
        initComponents();
    }

    private JPanel getRoot() {
        return (JPanel) this.getClientProperty("root");
    }

    private Business getBusiness() {
        return (Business) this.getClientProperty("business");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageAccounts = new javax.swing.JButton();
        btnManagePeople = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnManageAccounts.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnManageAccounts.setText("Manage User Accounts");
        btnManageAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccountsActionPerformed(evt);
            }
        });

        btnManagePeople.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnManagePeople.setText("Manage Students / Faculty");
        btnManagePeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePeopleActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnAnalytics.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnAnalytics.setText("Analytics Dashboard");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 204, 255));
        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnManagePeople)
                            .addComponent(btnLogout))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnLogout)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManagePeople, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccountsActionPerformed
        ManageUserAccountsPanel p = new ManageUserAccountsPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.refreshTable();
        getRoot().add("manageUserAccounts", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "manageUserAccounts");
    }//GEN-LAST:event_btnManageAccountsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        AdminProfilePanel p = new AdminProfilePanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", this.getClientProperty("account"));
        getRoot().add("adminProfile", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "adminProfile");
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnManagePeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePeopleActionPerformed
        ManagePeopleRecordsPanel p = new ManagePeopleRecordsPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.refreshPeopleTables();
        getRoot().add("managePeople", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "managePeople");
    }//GEN-LAST:event_btnManagePeopleActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        UniversityAnalyticsPanel p = new UniversityAnalyticsPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.generateAction();
        getRoot().add("analytics", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "analytics");
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "login");
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAccounts;
    private javax.swing.JButton btnManagePeople;
    private javax.swing.JButton btnProfile;
    // End of variables declaration//GEN-END:variables
}
