/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 * @author priyankavadivel
 * @author vedanarayananshrirangesh
 * @author rg
 */

package digitaluniversity.ui.student;

import model.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class StudentWorkAreaPanel extends javax.swing.JPanel {

    public StudentWorkAreaPanel() {
        initComponents();
    }

    private JPanel getRoot() {
        // Returns the parent container — used for CardLayout screen switching
        return (JPanel) this.getClientProperty("root");
    }

    private Business getBusiness() {
        // Retrieves central business model holding all data
        return (Business) this.getClientProperty("business");
    }

    private UserAccount getAccount() {
        // Gets the currently logged-in user account
        return (UserAccount) this.getClientProperty("account");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProgressAndGpa = new javax.swing.JButton();
        btnTutionBilling = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnCourseReg = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnProgressAndGpa.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnProgressAndGpa.setText("Progress & GPA");
        btnProgressAndGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgressAndGpaActionPerformed(evt);
            }
        });

        btnTutionBilling.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnTutionBilling.setText("Tuition/Billing");
        btnTutionBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutionBillingActionPerformed(evt);
            }
        });

        btnTranscript.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 204, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCourseReg.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCourseReg.setText("Course Registration");
        btnCourseReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRegActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCourseReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTranscript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProgressAndGpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTutionBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseReg)
                    .addComponent(btnProgressAndGpa))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTutionBilling)
                    .addComponent(btnTranscript))
                .addGap(50, 50, 50)
                .addComponent(btnProfile)
                .addGap(218, 218, 218))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Opens StudentProgressPanel and injects dependencies before switching view
    private void btnProgressAndGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgressAndGpaActionPerformed
        StudentProgressPanel p = new StudentProgressPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("progress", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "progress");
    }//GEN-LAST:event_btnProgressAndGpaActionPerformed
    // Opens tuition billing/payment screen for current student session
    private void btnTutionBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutionBillingActionPerformed
        TuitionPaymentPanel p = new TuitionPaymentPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("tuitionPayment", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "tuitionPayment");
    }//GEN-LAST:event_btnTutionBillingActionPerformed
    // Navigates to transcript history view with correct business + account context
    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        TranscriptPanel p = new TranscriptPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("transcript", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "transcript");
    }//GEN-LAST:event_btnTranscriptActionPerformed
    // Simply returns user to login screen via CardLayout
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "login");

    }//GEN-LAST:event_btnLogoutActionPerformed
    // Opens course registration panel for adding/dropping courses
    private void btnCourseRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRegActionPerformed
        CourseRegistrationPanel p = new CourseRegistrationPanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());
        getRoot().add("courseReg", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "courseReg");
    }//GEN-LAST:event_btnCourseRegActionPerformed
    // Opens editable student profile page (Name, Email, Program, etc.)
    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        StudentProfilePanel p = new StudentProfilePanel();
        p.putClientProperty("business", getBusiness());
        p.putClientProperty("root", getRoot());
        p.putClientProperty("account", getAccount());

        getRoot().add("studProfile", p);
        ((CardLayout) getRoot().getLayout()).show(getRoot(), "studProfile");
    }//GEN-LAST:event_btnProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseReg;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnProgressAndGpa;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JButton btnTutionBilling;
    // End of variables declaration//GEN-END:variables
}
